- name: 环境初始化
  hosts: "{{ lb_upstream_servers }}"
  vars:
    lb_upstream_servers: >-
      {{
        ((groups.k8s_master | default([])) + (groups.master_to_add | default([])))
        | difference(groups.master_to_delete | default([]))
        | unique
      }}
  roles:
    - kubernetes/kube-common
    - kubernetes/kube-init-master

