# playbook/scale-up-etcd.yml
---
- name: Scale up etcd cluster
  hosts: "{{ groups.etcd + groups.etcd_to_add | unique }}" 
  become: yes
  gather_facts: yes
  roles:
  - etcd/etcd-scale-up
- name: update confing 
  hosts: "{{ (groups.etcd | default([])) + (groups.etcd_to_add | default([])) | unique }}" 
  vars:
    etcd_initial_cluster_state: existing  
  become: yes
  tasks:
  - name: Sync etcd configuration to all cluster members
    include_tasks: roles/etcd/etcd-common/tasks/sync-etcd-config.yml

