- hosts: updatessh
  tasks:
  - name: copy1
    copy: src=/root/ansible-pro/update-openssh.tar.gz dest=/root backup=no 
  #- name: 测试
  #  shell: |
  #- name: 测试
  #copy: src=/etc/ansible/test.yaml dest=/tmp
  #register: test
  #delegate_to: "{{ add_master }}"
  #- name: test
  #debug:
  #  msg: "{{ test.stdout }}"
  #- name: 查看网卡
  #  shell: "ip a|grep '{{ host_ip }}/'|awk '{print $NF}'"
  #  register: network_name
  #- name: 测试
  #  debug:
  #    msg: "{{ network_name.stdout }} "
  #- name: 测试
  #  debug:
  #    var: network_name.stdout
  #- name: 检查服务状态
  #  shell: "systemctl status  mount-remote-kanas.service  |grep 'Active:'"
  #  register: kanas_status

  #- name: 输出mount-remote-kanas状态
  #  debug:
  #    msg: "{{ kanas_status.stdout }}"

