FROM  ubuntu:22.04 AS builder

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        libpcre2-dev \
        zlib1g-dev \
        libssl-dev \
        tar \
        gzip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY nginx-1.24.0.tar.gz .
RUN tar -xzf nginx-1.24.0.tar.gz && mv nginx-1.24.0 nginx
WORKDIR /src/nginx

# 动态编译，保留所有你需要的模块
RUN ./configure \
        --prefix=/data/nginx \
        --with-stream \
        --with-stream_ssl_module \
        --with-stream_realip_module \
        --with-http_ssl_module \
        --with-http_realip_module \
        --with-http_stub_status_module \
        --with-http_gzip_static_module \
        --with-pcre \
        --with-threads && \
    make -j$(nproc)

# 最终镜像只包含二进制
FROM ubuntu:22.04
RUN mkdir -p /data/nginx/sbin
COPY --from=builder /src/nginx/objs/nginx /data/nginx/sbin/nginx
CMD ["/data/nginx/sbin/nginx", "-g", "daemon off;"]
