FROM  ubuntu:22.04 AS builder

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        libssl-dev \
        libnl-3-dev \
        libnl-genl-3-dev \
        tar \
        gzip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY keepalived-2.3.4.tar.gz .
RUN tar -xzf keepalived-2.3.4.tar.gz && mv keepalived-2.3.4 keepalived
WORKDIR /src/keepalived

# 动态编译（不加 --disable-dynamic-linking）

RUN ./configure \
        --prefix=/usr/local \
        --sysconfdir=/etc/keepalived &&\
    make -j$(nproc)
FROM ubuntu:22.04
RUN mkdir -p /usr/local/sbin
COPY --from=builder /src/keepalived/keepalived /usr/local/sbin/keepalived
CMD ["/usr/local/sbin/keepalived", "-n"]
