# syntax=docker/dockerfile:1

ARG OS=ubuntu22

FROM rockylinux:8 AS base-rocky8
#FROM rockylinux:9 AS base-rocky9
FROM ubuntu:22.04 AS base-ubuntu22
FROM ubuntu:24.04 AS base-ubuntu24

FROM base-${OS} AS builder
ARG OS
ARG KEEPALIVED_VERSION=2.3.4
RUN if [ "$OS" = "ubuntu22" ] || [ "$OS" = "ubuntu24" ]; then \
        apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential libssl-dev libnl-3-dev libnl-genl-3-dev tar gzip && \
        rm -rf /var/lib/apt/lists/*; \
    elif [ "$OS" = "rocky8" ] || [ "$OS" = "rocky9" ]; then \
        dnf install -y gcc make openssl-devel libnl3-devel tar gzip && \
        dnf clean all; \
    fi

WORKDIR /src
#COPY keepalived-${KEEPALIVED_VERSION}.tar.gz .

#RUN tar -xzf keepalived-${KEEPALIVED_VERSION}.tar.gz && mv keepalived-${KEEPALIVED_VERSION} keepalived
ADD keepalived-${KEEPALIVED_VERSION}.tar.gz .


RUN mv  /src/keepalived-${KEEPALIVED_VERSION} /src/keepalived

WORKDIR /src/keepalived

RUN ./configure --prefix=/usr/local --sysconfdir=/etc/keepalived && \
    make -j$(nproc)

FROM scratch AS final
COPY --from=builder /src/keepalived/keepalived /keepalived
